-- 001_initial_schema.sql
-- Базовая схема Automata (расширенная форма ТА, schema: automata)

BEGIN;

CREATE SCHEMA IF NOT EXISTS automata;
SET search_path TO automata, public;

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS machine_statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS machine_models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_machine_models_brand_model UNIQUE (brand, model_name)
);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    phone VARCHAR(32) NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_users_email_format CHECK (email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE IF NOT EXISTS companies (
    id UUID PRIMARY KEY,
    parent_company_id UUID NULL REFERENCES companies(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    contact_person TEXT NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(320) NULL,
    address TEXT NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_companies_name_not_blank CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_companies_email_format CHECK (
        email IS NULL OR email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'
    )
);

CREATE INDEX IF NOT EXISTS ix_companies_name
    ON companies (name);

CREATE TABLE IF NOT EXISTS modems (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modem_number VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS product_matrices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS critical_value_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS notification_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS vending_machines (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location TEXT NOT NULL,
    machine_model_id INTEGER NOT NULL REFERENCES machine_models(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    slave_machine_model_id INTEGER NULL REFERENCES machine_models(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    status_id INTEGER NOT NULL REFERENCES machine_statuses(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    installed_at DATE NOT NULL,
    last_service_at DATE NULL,
    total_income NUMERIC(14, 2) NOT NULL DEFAULT 0,

    address TEXT NOT NULL,
    place TEXT NOT NULL,
    coordinates TEXT NULL,
    machine_number TEXT NOT NULL,
    operating_mode TEXT NOT NULL,
    working_hours TEXT NULL,
    time_zone TEXT NOT NULL,
    notes TEXT NULL,
    kit_online_cashbox_id TEXT NULL,
    service_priority TEXT NOT NULL,

    supports_coin_acceptor BOOLEAN NOT NULL DEFAULT FALSE,
    supports_bill_acceptor BOOLEAN NOT NULL DEFAULT FALSE,
    supports_cashless_module BOOLEAN NOT NULL DEFAULT FALSE,
    supports_qr_payments BOOLEAN NOT NULL DEFAULT FALSE,

    service_rfid_cards TEXT NULL,
    collection_rfid_cards TEXT NULL,
    loading_rfid_cards TEXT NULL,

    manager_user_id UUID NULL REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    engineer_user_id UUID NULL REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    technician_operator_user_id UUID NULL REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,

    client_name TEXT NULL,

    modem_id INTEGER NULL REFERENCES modems(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    product_matrix_id INTEGER NULL REFERENCES product_matrices(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    critical_value_template_id INTEGER NULL REFERENCES critical_value_templates(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    notification_template_id INTEGER NULL REFERENCES notification_templates(id) ON UPDATE RESTRICT ON DELETE RESTRICT,

    CONSTRAINT chk_vending_machines_total_income_nonnegative CHECK (total_income >= 0),
    CONSTRAINT chk_vending_machines_machine_number_not_blank CHECK (char_length(trim(machine_number)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vending_machines_machine_number
    ON vending_machines (machine_number);

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY,
    machine_id UUID NOT NULL REFERENCES vending_machines(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    min_stock INTEGER NOT NULL DEFAULT 0,
    avg_daily_sales NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT chk_products_price_positive CHECK (price > 0),
    CONSTRAINT chk_products_quantity_nonnegative CHECK (quantity >= 0),
    CONSTRAINT chk_products_min_stock_nonnegative CHECK (min_stock >= 0),
    CONSTRAINT chk_products_avg_daily_sales_nonnegative CHECK (avg_daily_sales >= 0)
);

CREATE TABLE IF NOT EXISTS sales (
    id UUID PRIMARY KEY,
    machine_id UUID NOT NULL REFERENCES vending_machines(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    product_id UUID NOT NULL REFERENCES products(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    sale_amount NUMERIC(12, 2) NOT NULL,
    sale_datetime TIMESTAMPTZ NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    CONSTRAINT chk_sales_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_sales_sale_amount_nonnegative CHECK (sale_amount >= 0)
);

CREATE TABLE IF NOT EXISTS maintenance_records (
    id UUID PRIMARY KEY,
    machine_id UUID NOT NULL REFERENCES vending_machines(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    service_date TIMESTAMPTZ NOT NULL,
    work_description TEXT NOT NULL,
    issues TEXT NULL
);

COMMIT;
